package sp;

import javax.swing.*;

/**
 *
 * @author user
 */
@SuppressWarnings("serial")
public class HelpDialog extends JDialog {

    private String helpText;
	/** Creates new form HelpDialog */
    public HelpDialog(String helpText) {
    	this.helpText = helpText;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        helpTitlePanel = new JPanel();
        helpLabel = new JLabel();
        helpScrollPane = new JScrollPane();
        helpTextArea = new JTextArea();
        helpSeparator = new JSeparator();


        helpLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        helpLabel.setText("Help");

        GroupLayout helpTitlePanelLayout = new GroupLayout(helpTitlePanel);
        helpTitlePanel.setLayout(helpTitlePanelLayout);
        helpTitlePanelLayout.setHorizontalGroup(
            helpTitlePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(helpTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpLabel)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        helpTitlePanelLayout.setVerticalGroup(
            helpTitlePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(helpTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpLabel)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        helpTextArea.setColumns(20);
        helpTextArea.setRows(5);
        helpScrollPane.setViewportView(helpTextArea);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(helpTitlePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(helpSeparator, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(helpScrollPane, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(helpTitlePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(helpSeparator, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpScrollPane, GroupLayout.PREFERRED_SIZE, 254, GroupLayout.PREFERRED_SIZE))
        );

        helpTextArea.setText(helpText);
        helpTextArea.setEditable(false);
        setModal(true);
        setResizable(false);
        pack();
       setLocationRelativeTo(null);
       setVisible(true);
    }// </editor-fold>

    // Variables declaration - do not modify
    private JLabel helpLabel;
    private JScrollPane helpScrollPane;
    private JSeparator helpSeparator;
    private JTextArea helpTextArea;
    private JPanel helpTitlePanel;
    // End of variables declaration
}
